name: Deploy Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Deploy Site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/configure-pages@v4
        with:
          static_site_generator: gatsby

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - uses: actions/cache@v3
        with:
          path: |
            ./client/public
            ./client/.cache
          key: ${{ runner.os }}-gatsby-build-${{ hashFiles('public') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-

      - run: yarn --frozen-lockfile

      - name: Build
        run: |
          cd client
          yarn build
        env:
          CI: "true"
          PREFIX_PATHS: "true"

      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./client/public

      - uses: actions/deploy-pages@v3
        id: deployment
